# Generated by Django 5.1.4 on 2026-05-15 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered')], default='pending', max_length=20)),
                ('from_buyer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_condition_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_createdat_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_cat_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='item_search_vector_idx',
        ),
        migrations.AlterField(
            model_name='itemeditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.item'),
        ),
        migrations.AddField(
            model_name='offer',
            name='parent_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='marketplace.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
