# Generated by Django 5.1.4 on 2026-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_sprint6_trust_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
